name: conda 编译 pyAAMED

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-2022

    steps:
    - name: 检出仓库代码
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: 设置 Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: 3.11
        activate-environment: pyaamed-env
        channels: conda-forge,defaults
        
    - name: 在 conda 环境中安装必要的包
      shell: pwsh
      run: |
        # 确保使用 conda 环境
        conda activate pyaamed-env
        
        # 使用 conda 安装所有包到当前环境
        conda install -y numpy cython opencv cmake compilers vs2019_win-64 vs2017_win-64
        conda install -y setuptools wheel pip
        
        # 验证安装 - 这些应该在 conda 环境中运行
        echo "=== 验证 conda 环境中的包 ==="
        conda list | grep -E "(numpy|cython|opencv)"
        python -c "import Cython; print('Cython版本:', Cython.__version__)"
        python -c "import numpy; print('NumPy版本:', numpy.__version__)"
        python -c "import cv2; print('OpenCV版本:', cv2.__version__)"

    - name: 检查目录结构
      shell: pwsh
      run: |
        conda activate pyaamed-env
        echo "当前目录结构:"
        Get-ChildItem -Recurse -Depth 2 | Select-Object Name
        echo "Python目录内容:"
        if (Test-Path "./python") {
            Get-ChildItem "./python"
        }

    - name: 编译 pyAAMED 扩展模块
      shell: pwsh
      run: |
        # 确保使用 conda 环境
        conda activate pyaamed-env
        
        # 再次验证关键包
        python -c "import Cython; print('Cython 可用')"
        python -c "import numpy; print('NumPy 可用')"
        python -c "import cv2; print('OpenCV 可用')"
        
        # 编译
        echo "开始编译..."
        cd ./python
        python setup.py build_ext --inplace
        
        echo "编译完成，检查生成的文件:"
        Get-ChildItem -Filter "*.pyd"
        Get-ChildItem -Filter "*.dll"

    - name: 验证编译输出并收集产物
      shell: pwsh
      run: |
        conda activate pyaamed-env
        
        # 创建产物目录
        New-Item -ItemType Directory -Path "artifacts" -Force
        
        echo "=== 查找生成的 pyd 文件 ==="
        $pydFiles = Get-ChildItem -Path "." -Recurse -Filter "*.pyd"
        if ($pydFiles) {
            foreach ($file in $pydFiles) {
                echo "找到 pyd 文件: $($file.FullName)"
                Copy-Item $file.FullName -Destination "artifacts/"
            }
        } else {
            echo "未找到 pyd 文件"
            # 尝试在 build 目录中查找
            echo "在 build 目录中查找:"
            Get-ChildItem -Path "." -Recurse -Filter "build" -Directory | ForEach-Object {
                Get-ChildItem -Path $_.FullName -Recurse -Filter "*.pyd"
            }
        }
        
        echo "=== 查找 pyAAMED 相关文件 ==="
        if (Test-Path "./python") {
            $pythonDirFiles = Get-ChildItem -Path "./python" -Filter "*AAMED*"
            foreach ($file in $pythonDirFiles) {
                echo "找到文件: $($file.Name)"
                if ($file.Extension -eq ".pyd" -or $file.Extension -eq ".dll") {
                    Copy-Item $file.FullName -Destination "artifacts/"
                }
            }
        }
        
        # 查找并复制 OpenCV DLL 依赖
        echo "=== 查找 OpenCV DLL 依赖 ==="
        $condaEnvPath = conda info --base
        $opencvDllPath = "$condaEnvPath\envs\pyaamed-env\Library\bin"
        
        if (Test-Path $opencvDllPath) {
            echo "在 $opencvDllPath 中查找 OpenCV DLL"
            $opencvDlls = Get-ChildItem -Path $opencvDllPath -Filter "opencv*.dll"
            foreach ($dll in $opencvDlls) {
                echo "复制 OpenCV DLL: $($dll.Name)"
                Copy-Item $dll.FullName -Destination "artifacts/"
            }
        }
        
        # 显示最终产物
        echo "=== 最终产物列表 ==="
        Get-ChildItem -Path "artifacts" -Recurse

    - name: 测试编译的模块
      shell: pwsh
      run: |
        conda activate pyaamed-env
        
        echo "=== 测试导入编译的模块 ==="
        if (Test-Path "./artifacts") {
            cd ./artifacts
            try {
                python -c "import sys; sys.path.append('.'); import pyAAMED; print('成功导入 pyAAMED 模块')"
            } catch {
                echo "导入模块失败: $($_.Exception.Message)"
                echo "当前目录内容:"
                Get-ChildItem
            }
        } else {
            echo "artifacts 目录不存在，跳过测试"
        }

    - name: 打包产物
      shell: pwsh
      run: |
        if (Test-Path "./artifacts") {
            # 创建版本信息
            $version = Get-Date -Format "yyyyMMdd-HHmmss"
            $zipName = "pyAAMED-windows-$version.zip"
            
            # 压缩产物
            Compress-Archive -Path "artifacts/*" -DestinationPath $zipName
            
            echo "生成压缩包: $zipName"
            Get-ChildItem -Filter "*.zip"
        } else {
            echo "没有产物可打包"
        }

    - name: 上传构建产物
      uses: actions/upload-artifact@v4
      with:
        name: pyAAMED-windows-build
        path: |
          artifacts/
          *.zip
        retention-days: 30
      if: success() || failure()

    - name: 显示构建信息
      shell: pwsh
      run: |
        conda activate pyaamed-env
        echo "=== 构建环境信息 ==="
        python --version
        echo "=== Conda 环境列表 ==="
        conda info --envs
        echo "=== 当前环境路径 ==="
        conda info --base
        echo "=== 已安装的包 ==="
        conda list | grep -E "(numpy|cython|opencv|setuptools|wheel|pip)"